### ISSUE TITLE
TUSB2077A USB hub

### ISSUE THREAD

**Issue by ottopasuuna** [UofSSpaceDesignTeam/rover-hardware#17]
Make a usb hub based on the TUSB2077A chip by TI.
- [X] remove over current protection (for simplicity)
- [X] Invesigate/remove resistor network
- [X] Simplify connector circuits
- [x] Redo layout

**Comment by ausshir** [comment]
Should we make sure to use through-hole USB A plugs? The reference design seems To use SMT but I'd be afaird of the big plug tearing off the pads.

**Comment by ottopasuuna** [comment]
Yeah, that sounds like a good idea.

**Comment by ottopasuuna** [comment]
This is basically done. It needs a proper reset circuit; either a power-on reset chip, or an rc circuit that properly discharges after a sudden power down. All the ports seem to work, and the rover can communicate to VESCs plugged into it without issues.
