### ISSUE TITLE
Arm Board PCB Issues

### ISSUE THREAD

**Issue by LiamBindle** [UofSSpaceDesignTeam/rover-hardware#2]
This is just a list of the issues with the [arm-board-0.1](https://github.com/UofSSpaceDesignTeam/rover-electrical/tree/master/Projects/arm_board/arm_board-0.1) for future reference.
## Issues
- Opto-isolator footprint is not correct
- 5V footprint is not correct
- Count UP/DOWN input AND gate should actually be a NAND gate
- The ~~AND~~ NAND gate should be on the other side of the opto-isolators
- The voltage levels are mixed up on the noise side of the opto-isolators

**Comment by ottopasuuna** [comment]
I think this board has been abandoned. Are we good to close this issue?
