### ISSUE TITLE
VESC modifications V1

### ISSUE THREAD

**Issue by ottopasuuna** [UofSSpaceDesignTeam/rover-hardware#6]
Modify the pcb to remove componets we don't need and make it smaller. Also, use better connectors

- [x] Assembly
- [x] Testing

**Comment by ausshir** [comment]
### Proposed Modifications to the Schematic
- [ ] Remove switching power supply and change to LDO (low-drop-out) regulators to power it from USB 5v (the same hardware as the Raspberry Pi should be good for this)
- [ ] Change the SWD connector to just testpoint pads (for initial programming or recovery).
- [ ] Remove CAN bus (maybe?)
- [ ] Change USB connector from Mini B to something more robust to match the rest of the rover.
- [ ] Merge the Hall sensor connector with the motor power connector onto a Molex Mini Fir Jr 8-pin
- [ ] Add a breakout for the Hall sensor pins to be used as encoder or SPI (Needs more detail)

I will add the VESC files soon. There is a new hardware revision coming out but we might be best sticking to the previous one as there are likely bugs in the new one!

**Comment by ausshir** [comment]
We have ordered some card edge connectors [TE 1761426-2](http://www.te.com/usa-en/product-1761426-2.html) and are looking into how these can work for us.

Also, looking into how removing the buck converter on the DRV8302 would affect operation.

We have access to the new VESCv6 files, so also looking into the benefits of the added complexity or if we should keep the design simpler and stick to well-tested parts.

**Comment by ottopasuuna** [comment]
We'll create a new issue for the version 2...
